lane_planner:
    map_frame_id : map
    lane_width : 2.5
    vehicle_width : 0.65
    sampling_number : 9
    distanceCost_gain : 1.0
    obstacleCost_gain : 10
    markerSize : 4.0
    maxVelocity : 1.1
    distanceTarget_maxVelocity : 4.0 #3
    distance_rate : 0.5 #0.6
    loop_rate : 20