my_costmap:
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: floor
  robot_base_frame: base_link
  footprint: [[0.2,0.22], [-0.55,0.22], [-0.55,-0.22], [0.2,-0.22]]
  #footprint: [[-0.55, 0], [-0.5, 0.38], [0, 0.55], [0.48, 0.38], [0.55, 0], [0.48, -0.38], [0, -0.55], [-0.5, -0.38]]
  rolling_window: true
  width: 40.0
  height: 40.0
  resolution: 0.1
  update_frequency: 20.0
  publish_frequency: 20.0

  obstacle_layer:
    observation_sources: laser_scan_sensor
    clearing: true
    laser_scan_sensor:
      #sensor_frame: camera_link
      #topic: scan
      #data_type: LaserScan
      sensor_frame: velodyne
      topic: velodyne_points
      data_type: PointCloud2
      min_obstacle_height : 0.3
      #sensor_frame: floor
      #topic: mapcloud
      #data_type: PointCloud2
      marking: true
      clearing: true
      obstacle_range : 5.5
      raytrace_range : 6.0

      inf_is_valid: true
  inflation_layer:
    inflation_radius: 2
    cost_scaling_factor : 2.5

  path_costmap:
    cost_path_width: 4.0
    use_dynamic_path_width: true